# Generated by Django 4.2.26 on 2026-03-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0096_job_last_frame"),
        ("engine", "0097_alter_relatedfile_path"),
    ]

    operations = []
