# Generated by Django 4.2.28 on 2026-08-04 23:28

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0098_merge_0096_job_last_frame_0097_alter_relatedfile_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="stage",
            field=models.CharField(
                choices=[
                    ("annotation", "ANNOTATION"),
                    ("validation", "VALIDATION"),
                    ("validation1", "VALIDATION1"),
                    ("validation2", "VALIDATION2"),
                    ("validation3", "VALIDATION3"),
                    ("validation4", "VALIDATION4"),
                    ("validation5", "VALIDATION5"),
                    ("validation6", "VALIDATION6"),
                    ("validation7", "VALIDATION7"),
                    ("validation8", "VALIDATION8"),
                    ("validation9", "VALIDATION9"),
                    ("validation10", "VALIDATION10"),
                    ("acceptance", "ACCEPTANCE"),
                ],
                default=cvat.apps.engine.models.StageChoice["ANNOTATION"],
                max_length=32,
            ),
        ),
    ]
